//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the traj_gen package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __traj_gen__CONTROLLERDYNCONFIG_H__
#define __traj_gen__CONTROLLERDYNCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace traj_gen
{
  class controllerDynConfigStatics;

  class controllerDynConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(controllerDynConfig &config, const controllerDynConfig &max, const controllerDynConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const controllerDynConfig &config1, const controllerDynConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, controllerDynConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const controllerDynConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, controllerDynConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const controllerDynConfig &config) const = 0;
      virtual void getValue(const controllerDynConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T controllerDynConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T controllerDynConfig::* field;

      virtual void clamp(controllerDynConfig &config, const controllerDynConfig &max, const controllerDynConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const controllerDynConfig &config1, const controllerDynConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, controllerDynConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const controllerDynConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, controllerDynConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const controllerDynConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const controllerDynConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, controllerDynConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, controllerDynConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<controllerDynConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(controllerDynConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("test_mode"==(*_i)->name){test_mode = boost::any_cast<int>(val);}
      }
    }

    int test_mode;

    bool state;
    std::string name;

    class GROUP_CONTROL
{
  public:
    GROUP_CONTROL()
    {
      state = true;
      name = "group_control";
    }

    void setParams(controllerDynConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_take_off"==(*_i)->name){enable_take_off = boost::any_cast<bool>(val);}
        if("enable_landing"==(*_i)->name){enable_landing = boost::any_cast<bool>(val);}
      }
    }

    bool enable_take_off;
bool enable_landing;

    bool state;
    std::string name;

    
}group_control;

}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int test_mode;
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      bool enable_take_off;
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      bool enable_landing;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("controllerDynConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const controllerDynConfig &__max__ = __getMax__();
      const controllerDynConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const controllerDynConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const controllerDynConfig &__getDefault__();
    static const controllerDynConfig &__getMax__();
    static const controllerDynConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const controllerDynConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void controllerDynConfig::ParamDescription<std::string>::clamp(controllerDynConfig &config, const controllerDynConfig &max, const controllerDynConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class controllerDynConfigStatics
  {
    friend class controllerDynConfig;

    controllerDynConfigStatics()
    {
controllerDynConfig::GroupDescription<controllerDynConfig::DEFAULT, controllerDynConfig> Default("Default", "", 0, 0, true, &controllerDynConfig::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.test_mode = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.test_mode = 6;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.test_mode = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<int>("test_mode", "int", 0, "test mode", "{'enum_description': 'An enum to chose test mode', 'enum': [{'srcline': 22, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_Z'}, {'srcline': 23, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_PSI'}, {'srcline': 24, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_X'}, {'srcline': 25, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_Y'}, {'srcline': 26, 'description': 'Circular tracking test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_CIRCLE'}, {'srcline': 27, 'description': 'Figure 8 test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_8'}, {'srcline': 28, 'description': 'Trajectory tracking test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 6, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_TRAJ'}]}", &controllerDynConfig::test_mode)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<int>("test_mode", "int", 0, "test mode", "{'enum_description': 'An enum to chose test mode', 'enum': [{'srcline': 22, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_Z'}, {'srcline': 23, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_PSI'}, {'srcline': 24, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_X'}, {'srcline': 25, 'description': 'Step z test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'TEST_STEP_Y'}, {'srcline': 26, 'description': 'Circular tracking test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 4, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_CIRCLE'}, {'srcline': 27, 'description': 'Figure 8 test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 5, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_8'}, {'srcline': 28, 'description': 'Trajectory tracking test', 'srcfile': '/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg', 'cconsttype': 'const int', 'value': 6, 'ctype': 'int', 'type': 'int', 'name': 'TEST_TRACKING_TRAJ'}]}", &controllerDynConfig::test_mode)));
controllerDynConfig::GroupDescription<controllerDynConfig::DEFAULT::GROUP_CONTROL, controllerDynConfig::DEFAULT> group_control("group_control", "", 0, 1, true, &controllerDynConfig::DEFAULT::group_control);
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __min__.enable_take_off = 0;
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __max__.enable_take_off = 1;
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __default__.enable_take_off = 0;
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      group_control.abstract_parameters.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<bool>("enable_take_off", "bool", 1, "enable take off", "", &controllerDynConfig::enable_take_off)));
//#line 35 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __param_descriptions__.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<bool>("enable_take_off", "bool", 1, "enable take off", "", &controllerDynConfig::enable_take_off)));
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __min__.enable_landing = 0;
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __max__.enable_landing = 1;
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __default__.enable_landing = 0;
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      group_control.abstract_parameters.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<bool>("enable_landing", "bool", 1, "enable landing", "", &controllerDynConfig::enable_landing)));
//#line 36 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      __param_descriptions__.push_back(controllerDynConfig::AbstractParamDescriptionConstPtr(new controllerDynConfig::ParamDescription<bool>("enable_landing", "bool", 1, "enable landing", "", &controllerDynConfig::enable_landing)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      group_control.convertParams();
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(controllerDynConfig::AbstractGroupDescriptionConstPtr(new controllerDynConfig::GroupDescription<controllerDynConfig::DEFAULT::GROUP_CONTROL, controllerDynConfig::DEFAULT>(group_control)));
//#line 124 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(controllerDynConfig::AbstractGroupDescriptionConstPtr(new controllerDynConfig::GroupDescription<controllerDynConfig::DEFAULT::GROUP_CONTROL, controllerDynConfig::DEFAULT>(group_control)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(controllerDynConfig::AbstractGroupDescriptionConstPtr(new controllerDynConfig::GroupDescription<controllerDynConfig::DEFAULT, controllerDynConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<controllerDynConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<controllerDynConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<controllerDynConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    controllerDynConfig __max__;
    controllerDynConfig __min__;
    controllerDynConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const controllerDynConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static controllerDynConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &controllerDynConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const controllerDynConfig &controllerDynConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const controllerDynConfig &controllerDynConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const controllerDynConfig &controllerDynConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<controllerDynConfig::AbstractParamDescriptionConstPtr> &controllerDynConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<controllerDynConfig::AbstractGroupDescriptionConstPtr> &controllerDynConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const controllerDynConfigStatics *controllerDynConfig::__get_statics__()
  {
    const static controllerDynConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = controllerDynConfigStatics::get_instance();

    return statics;
  }

//#line 11 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_ENABLE_CTRL = 1;
//#line 22 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_STEP_Z = 0;
//#line 23 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_STEP_PSI = 1;
//#line 24 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_STEP_X = 2;
//#line 25 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_STEP_Y = 3;
//#line 26 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_TRACKING_CIRCLE = 4;
//#line 27 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_TRACKING_8 = 5;
//#line 28 "/home/fechec/feng_ws/src/traj_gen/cfg/controllerDyn.cfg"
      const int controllerDyn_TEST_TRACKING_TRAJ = 6;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CONTROLLERDYNRECONFIGURATOR_H__
