// Generated by gencpp from file target_detection/target_dect_msg.msg
// DO NOT EDIT!


#ifndef TARGET_DETECTION_MESSAGE_TARGET_DECT_MSG_H
#define TARGET_DETECTION_MESSAGE_TARGET_DECT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace target_detection
{
template <class ContainerAllocator>
struct target_dect_msg_
{
  typedef target_dect_msg_<ContainerAllocator> Type;

  target_dect_msg_()
    : header()
    , position_ref()
    , velocity_ref()
    , accel_ref()
    , jerk_ref()
    , snap_ref()
    , yaw_ref()
    , launch_flag(false)
    , speed(0.0)
    , collide_state(false)  {
      yaw_ref.assign(0.0);
  }
  target_dect_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_ref(_alloc)
    , velocity_ref(_alloc)
    , accel_ref(_alloc)
    , jerk_ref(_alloc)
    , snap_ref(_alloc)
    , yaw_ref()
    , launch_flag(false)
    , speed(0.0)
    , collide_state(false)  {
  (void)_alloc;
      yaw_ref.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _position_ref_type;
  _position_ref_type position_ref;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_ref_type;
  _velocity_ref_type velocity_ref;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _accel_ref_type;
  _accel_ref_type accel_ref;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _jerk_ref_type;
  _jerk_ref_type jerk_ref;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _snap_ref_type;
  _snap_ref_type snap_ref;

   typedef boost::array<double, 3>  _yaw_ref_type;
  _yaw_ref_type yaw_ref;

   typedef uint8_t _launch_flag_type;
  _launch_flag_type launch_flag;

   typedef double _speed_type;
  _speed_type speed;

   typedef uint8_t _collide_state_type;
  _collide_state_type collide_state;





  typedef boost::shared_ptr< ::target_detection::target_dect_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::target_detection::target_dect_msg_<ContainerAllocator> const> ConstPtr;

}; // struct target_dect_msg_

typedef ::target_detection::target_dect_msg_<std::allocator<void> > target_dect_msg;

typedef boost::shared_ptr< ::target_detection::target_dect_msg > target_dect_msgPtr;
typedef boost::shared_ptr< ::target_detection::target_dect_msg const> target_dect_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::target_detection::target_dect_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::target_detection::target_dect_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::target_detection::target_dect_msg_<ContainerAllocator1> & lhs, const ::target_detection::target_dect_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position_ref == rhs.position_ref &&
    lhs.velocity_ref == rhs.velocity_ref &&
    lhs.accel_ref == rhs.accel_ref &&
    lhs.jerk_ref == rhs.jerk_ref &&
    lhs.snap_ref == rhs.snap_ref &&
    lhs.yaw_ref == rhs.yaw_ref &&
    lhs.launch_flag == rhs.launch_flag &&
    lhs.speed == rhs.speed &&
    lhs.collide_state == rhs.collide_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::target_detection::target_dect_msg_<ContainerAllocator1> & lhs, const ::target_detection::target_dect_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace target_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::target_dect_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::target_detection::target_dect_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::target_dect_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::target_detection::target_dect_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::target_dect_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::target_detection::target_dect_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::target_detection::target_dect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a847c4ada344c2340bcd2fb12cdd132";
  }

  static const char* value(const ::target_detection::target_dect_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a847c4ada344c23ULL;
  static const uint64_t static_value2 = 0x40bcd2fb12cdd132ULL;
};

template<class ContainerAllocator>
struct DataType< ::target_detection::target_dect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "target_detection/target_dect_msg";
  }

  static const char* value(const ::target_detection::target_dect_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::target_detection::target_dect_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# references\n"
"geometry_msgs/Vector3 position_ref\n"
"geometry_msgs/Vector3 velocity_ref\n"
"geometry_msgs/Vector3 accel_ref\n"
"geometry_msgs/Vector3 jerk_ref\n"
"geometry_msgs/Vector3 snap_ref\n"
"float64[3] yaw_ref\n"
"bool launch_flag\n"
"float64 speed\n"
"bool collide_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::target_detection::target_dect_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::target_detection::target_dect_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position_ref);
      stream.next(m.velocity_ref);
      stream.next(m.accel_ref);
      stream.next(m.jerk_ref);
      stream.next(m.snap_ref);
      stream.next(m.yaw_ref);
      stream.next(m.launch_flag);
      stream.next(m.speed);
      stream.next(m.collide_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct target_dect_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::target_detection::target_dect_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::target_detection::target_dect_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.position_ref);
    s << indent << "velocity_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity_ref);
    s << indent << "accel_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.accel_ref);
    s << indent << "jerk_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.jerk_ref);
    s << indent << "snap_ref: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.snap_ref);
    s << indent << "yaw_ref[]" << std::endl;
    for (size_t i = 0; i < v.yaw_ref.size(); ++i)
    {
      s << indent << "  yaw_ref[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.yaw_ref[i]);
    }
    s << indent << "launch_flag: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.launch_flag);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "collide_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collide_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TARGET_DETECTION_MESSAGE_TARGET_DECT_MSG_H
